name: Licences tests
on:
  push:
  pull_request:
    # Do not run when only tests are updated
    paths-ignore:
      - 'tests/UI/**'

permissions:
  contents: read   #   to clone the repos and get release assets (shivammathur/setup-php)
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  licences:
    permissions:
      contents: read   #   to clone the repos and get release assets (shivammathur/setup-php)
    name: Licences check
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer Install
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Run licences update
        run: php bin/console prestashop:licenses:update
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled

      - name: Test git versionned files unchanged
        if: ${{ !startsWith(matrix.php, '8.') }}  # composer.lock changes when updating phpunit version
        run: git diff --exit-code
